[project]
name = "projects"
version = "1.0.1"
description = "Manage python projects"
authors = [{name = "Jeff Watkins", email = "jeffwatkins2000@gmail.com"}]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "clipboard>=0.0.4",
    "dotenv>=0.9.9",
    "json5>=0.15.0",
    "psiutils>=1.0.2",
    "python-dateutil>=2.9.0.post0",
    "tksheet>=7.6.0",
]

[tool.ruff]
line-length = 79
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]  # pycodestyle, pyflakes, isort
ignore = []

[dependency-groups]
dev = [
    "pytest",
    "jedi>=0.19.2",
    "ruff>=0.11.0",
]

[build-system]
requires = ['uv-build']
build-backend = 'uv_build'
